### ISSUE TITLE
Data gathering from CS:GO is slow

### ISSUE THREAD

**Issue by Sebight** [ShaunLWM/node-csgo-gsi#16] opened 2021-11-03 09:13 UTC
CS:GO data as health,... is gathered slowly, which results in HUD not being "live" but more like being updated every 1-5 seconds.

This is my cfg file.

`"node-csgo-gsi"
{
	"uri" "http://127.0.0.1:3000"
	"timeout" "5.0"
	"buffer"  "0.1"
	"throttle" "0.1"
	"heartbeat" "30.0"
	"auth"
	{
		"token" "Q79v5tcxVQ8u"
	}
	"data"
	{
		"provider"            "1"
   		"map"                 "1"
  		 "round"               "1"
   		"player_id"           "1"
   		"allplayers_id"       "1"      // Same as 'player_id' but for all players. 'allplayers' versions are only valid for HLTV and observers
   		"player_state"        "1"      
   		"allplayers_state"    "1"      
   		"allplayers_match_stats"  "1"  
   		"allplayers_weapons"  "1"      
   		"allplayers_position" "1"      // output the player world positions, only valid for GOTV or spectators. 
   		"phase_countdowns"    "1"      // countdowns of each second remaining for game phases, eg round time left, time until bomb explode, freezetime. Only valid for GOTV or spectators. 
   		"allgrenades"    "1"           // output information about all grenades and inferno flames in the world, only valid for GOTV or spectators.
	}
}`

I've implemented my own "alldata" in the library's code to send all data

process(data) {

       this.emit("alldata", data);
       

I then send this via soccket to website, but it is not caused by the socke itself, but rather with CS:GO. (Even when I console.log the data, the updating is slow.)

**Comment by atiernan** [comment] 2022-02-11 16:08
This is caused by #12, the fix was merged but never released to NPM.

@ShaunLWM would it be possible to get a release to NPM?

**Comment by ShaunLWM** [comment] 2022-02-12 00:35
Publish on 0.0.5. Sorry about that. I haven't touch CS:GO in years. 😥

**Closed by ShaunLWM** 2022-02-12 00:35 UTC
